/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tienda;

import java.util.HashMap;
import java.util.Map;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class inventory extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_tittle = new javax.swing.JLabel();
        lab_id = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        lb_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        lb_purchase_price = new javax.swing.JLabel();
        tf_purchase_price = new javax.swing.JTextField();
        lb_sale_price = new javax.swing.JLabel();
        tf_sale_price = new javax.swing.JTextField();
        lb_quantity = new javax.swing.JLabel();
        tf_quantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_inventory = new javax.swing.JTable();
        btn_create = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab_tittle.setText("Inventory");

        lab_id.setText("ID");

        tf_id.setEnabled(false);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        lb_name.setText("Name");

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        lb_purchase_price.setText("Purchase price");

        tf_purchase_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_purchase_priceActionPerformed(evt);
            }
        });

        lb_sale_price.setText("Sale price");

        tf_sale_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sale_priceActionPerformed(evt);
            }
        });

        lb_quantity.setText("Quantity");

        tf_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_quantityActionPerformed(evt);
            }
        });

        tbl_inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Purchase price", "Sale price", "Quantity"
            }
        ));
        tbl_inventory.setEnabled(false);
        tbl_inventory.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_inventory);

        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });

        btn_read.setText("Read");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update(evt);
            }
        });

        JButton.setText("Tienda");
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lab_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_quantity)
                                            .addComponent(lb_sale_price)
                                            .addComponent(lb_purchase_price))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_purchase_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_sale_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tf_quantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_create)
                                    .addComponent(btn_delete)
                                    .addComponent(btn_read)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JButton)))))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_tittle)
                    .addComponent(lab_id)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_name)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_create))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_purchase_price)
                    .addComponent(tf_purchase_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_sale_price)
                    .addComponent(tf_sale_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_read))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_quantity)
                    .addComponent(tf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update)
                    .addComponent(JButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_purchase_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_purchase_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_purchase_priceActionPerformed

    private void tf_sale_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sale_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sale_priceActionPerformed

    private void tf_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_quantityActionPerformed

    private void clean() {
        tf_id.setText("");
        tf_name.setText("");
        tf_purchase_price.setText("");
        tf_sale_price.setText("");
        tf_quantity.setText("");
    }

    private void table_update() {
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_inventory.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[] {
                    fila.get("id"),
                    fila.get("name"),
                    fila.get("purchase_price"),
                    fila.get("sale_price"),
                    fila.get("quantity"),
            });
        }
    }
    
    private void delete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete
        // TODO add your handling code here:
        int id = Integer.parseInt(tf_id.getText());
        bd.borrar(id, configuration, tabla);
        
        clean();
        table_update();
    }//GEN-LAST:event_delete

    private void read(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read
        // TODO add your handling code here:
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_inventory.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[] {
                    fila.get("id"),
                    fila.get("name"),
                    fila.get("purchase_price"),
                    fila.get("sale_price"),
                    fila.get("quantity"),
            });
        }
    }//GEN-LAST:event_read

    private void update(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update
        // TODO add your handling code here:
        int id = Integer.parseInt(tf_id.getText());
        Map datos = new HashMap();
        datos.put(campos[0], tf_name.getText());
        datos.put(campos[1], tf_purchase_price.getText());
        datos.put(campos[2], tf_sale_price.getText());
        datos.put(campos[3], tf_quantity.getText());
        
        bd.actualizar(id, datos, configuration, tabla);
        
        clean();
        table_update();
    }//GEN-LAST:event_update

    private void create(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create
        // TODO add your handling code here:
        Map datos = new HashMap();
        datos.put(campos[0], tf_name.getText());
        datos.put(campos[1], tf_purchase_price.getText());
        datos.put(campos[2], tf_sale_price.getText());
        datos.put(campos[3], tf_quantity.getText());
        
        bd.crear(datos, configuration, tabla);
        
        clean();
        table_update();
    }//GEN-LAST:event_create

    private void JButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new inventory().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_id;
    private javax.swing.JLabel lab_tittle;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_purchase_price;
    private javax.swing.JLabel lb_quantity;
    private javax.swing.JLabel lb_sale_price;
    private javax.swing.JTable tbl_inventory;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_purchase_price;
    private javax.swing.JTextField tf_quantity;
    private javax.swing.JTextField tf_sale_price;
    // End of variables declaration//GEN-END:variables
    
    String [] configuration = {"localhost", "root", "adminadmin", "portfolio"};
    String tabla = "inventory";
    String [] campos = {"name", "purchase_price", "sale_price", "quantity"};
    MySQLGenerico bd = new MySQLGenerico();
}
