/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tienda;

import java.util.HashMap;
import java.util.Map;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class tienda extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
    public tienda() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_tittle = new javax.swing.JLabel();
        lab_id = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        lb_product_name = new javax.swing.JLabel();
        tf_product_name = new javax.swing.JTextField();
        lb_sale_price = new javax.swing.JLabel();
        tf_unit_price = new javax.swing.JTextField();
        lb_quantities_sold = new javax.swing.JLabel();
        tf_quantities_sold = new javax.swing.JTextField();
        JButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tienda = new javax.swing.JTable();
        btn_create = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        lb_date_sale = new javax.swing.JLabel();
        tf_date_sale = new javax.swing.JTextField();
        lb_total = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        JButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab_tittle.setText("Inventory");

        lab_id.setText("ID");

        tf_id.setEnabled(false);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id(evt);
            }
        });

        lb_product_name.setText("Product Name");

        tf_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_product_name(evt);
            }
        });

        lb_sale_price.setText("Unit price");

        tf_unit_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_unit_price(evt);
            }
        });

        lb_quantities_sold.setText("Quantities sold");

        tf_quantities_sold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_quantities_sold(evt);
            }
        });

        JButton.setText("Inventory");
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton(evt);
            }
        });

        tbl_tienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Quantities sold", "Unit price", "Date sale", "Total"
            }
        ));
        tbl_tienda.setEnabled(false);
        tbl_tienda.getTableHeader().setReorderingAllowed(false);
        tbl_tienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                get_data(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tienda);

        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create(evt);
            }
        });

        btn_read.setText("Read");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read(evt);
            }
        });

        lb_date_sale.setText("Date sale");

        tf_date_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_date_sale(evt);
            }
        });

        lb_total.setText("Total");

        tf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_total(evt);
            }
        });

        JButton1.setText("Reports");
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lab_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lb_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_quantities_sold)
                                            .addComponent(lb_sale_price))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_quantities_sold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_date_sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lb_date_sale))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_create)
                                        .addGap(18, 18, 18)
                                        .addComponent(JButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lb_total)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_read)
                                        .addGap(18, 18, 18)
                                        .addComponent(JButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_tittle)
                    .addComponent(lab_id)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_product_name)
                    .addComponent(tf_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_read)
                        .addComponent(JButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_sale_price)
                            .addComponent(tf_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_quantities_sold)
                            .addComponent(tf_quantities_sold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_create)
                            .addComponent(JButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_date_sale)
                    .addComponent(tf_date_sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_total)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_id(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id

    private void tf_product_name(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_product_name
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_product_name

    private void tf_unit_price(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_unit_price
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_unit_price

    private void tf_quantities_sold(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_quantities_sold
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_quantities_sold

    private void clean() {
        tf_id.setText("");
        tf_product_name.setText("");
        tf_quantities_sold.setText("");
        tf_unit_price.setText("");
        tf_date_sale.setText("");
        tf_total.setText("");
    }

    private void table_update() {
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_tienda.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[] {
                    fila.get("id"),
                    fila.get("product_name"),
                    fila.get("quantities_sold"),
                    fila.get("unit_price"),
                    fila.get("date_sale"),
                    fila.get("total"),
            });
        }
    }
    
    private void read(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read
        // TODO add your handling code here:
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_tienda.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[] {
                    fila.get("id"),
                    fila.get("product_name"),
                    fila.get("quantities_sold"),
                    fila.get("unit_price"),
                    fila.get("date_sale"),
                    fila.get("total"),
            });
        }
    }//GEN-LAST:event_read

    private void create(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create
        // TODO add your handling code here:
        Map datos = new HashMap();
        datos.put(campos[0], tf_product_name.getText());
        datos.put(campos[1], tf_quantities_sold.getText());
        datos.put(campos[2], tf_unit_price.getText());
        datos.put(campos[3], tf_date_sale.getText());
        datos.put(campos[4], tf_total.getText());
        
        bd.crear(datos, configuration, tabla);

        clean();
        table_update();
    }//GEN-LAST:event_create

    private void tf_date_sale(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_date_sale
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_date_sale

    private void tf_total(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_total
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_total

    private void get_data(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_data
        // TODO add your handling code here:
        int fila = tbl_tienda.getSelectedRow();
        if (fila >= 0){
            tf_id.setText(tbl_tienda.getValueAt(fila, 0).toString());
            tf_product_name.setText(tbl_tienda.getValueAt(fila, 1).toString());
            tf_quantities_sold.setText(tbl_tienda.getValueAt(fila, 2).toString());
            tf_unit_price.setText(tbl_tienda.getValueAt(fila, 3).toString());
            tf_date_sale.setText(tbl_tienda.getValueAt(fila, 4).toString());
            tf_total.setText(tbl_tienda.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_get_data

    private void JButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton
        // TODO add your handling code here:
        new inventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButton

    private void JButton1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButton1

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton;
    private javax.swing.JButton JButton1;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_read;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_id;
    private javax.swing.JLabel lab_tittle;
    private javax.swing.JLabel lb_date_sale;
    private javax.swing.JLabel lb_product_name;
    private javax.swing.JLabel lb_quantities_sold;
    private javax.swing.JLabel lb_sale_price;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTable tbl_tienda;
    private javax.swing.JTextField tf_date_sale;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_product_name;
    private javax.swing.JTextField tf_quantities_sold;
    private javax.swing.JTextField tf_total;
    private javax.swing.JTextField tf_unit_price;
    // End of variables declaration//GEN-END:variables

    String [] configuration = {"localhost", "root", "adminadmin", "portfolio"};
    String tabla = "sales";  
    String [] campos = {"product_name", "quantities_sold", "unit_price", "date_sale", "total"};
    MySQLGenerico bd = new MySQLGenerico();
}
