/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tienda;

import java.util.HashMap;
import java.util.Map;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class tienda extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
    public tienda() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_tittle = new javax.swing.JLabel();
        lab_id = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        lb_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        lb_sale_price = new javax.swing.JLabel();
        tf_unit_price = new javax.swing.JTextField();
        lb_quantities_sold = new javax.swing.JLabel();
        tf_quantities_sold = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tienda = new javax.swing.JTable();
        btn_create = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        lb_date_sale = new javax.swing.JLabel();
        tf_date_sale = new javax.swing.JTextField();
        lb_total = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab_tittle.setText("Inventory");

        lab_id.setText("ID");

        tf_id.setEnabled(false);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        lb_name.setText("Name");

        tf_name.setEnabled(false);
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        lb_sale_price.setText("Unit price");

        tf_unit_price.setEnabled(false);
        tf_unit_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_unit_priceActionPerformed(evt);
            }
        });

        lb_quantities_sold.setText("Quantities sold");

        tf_quantities_sold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_quantities_soldActionPerformed(evt);
            }
        });

        tbl_tienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Quantities sold", "Unit price", "Date sale", "Total"
            }
        ));
        tbl_tienda.setEnabled(false);
        tbl_tienda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_tienda);

        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create(evt);
            }
        });

        btn_read.setText("Read");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read(evt);
            }
        });

        lb_date_sale.setText("Date sale");

        tf_date_sale.setEnabled(false);
        tf_date_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_date_saleActionPerformed(evt);
            }
        });

        lb_total.setText("Total");

        tf_total.setEnabled(false);
        tf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab_tittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lab_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_quantities_sold)
                                            .addComponent(lb_sale_price))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_quantities_sold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_date_sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lb_date_sale))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_create)
                                    .addComponent(btn_read)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lb_total))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_tittle)
                    .addComponent(lab_id)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_name)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_read)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_sale_price)
                            .addComponent(tf_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_quantities_sold)
                            .addComponent(tf_quantities_sold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_create))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_date_sale)
                    .addComponent(tf_date_sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_total)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_unit_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_unit_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_unit_priceActionPerformed

    private void tf_quantities_soldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_quantities_soldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_quantities_soldActionPerformed

    private void clean() {
        tf_id.setText("");
        tf_name.setText("");
        tf_quantities_sold.setText("");
        tf_unit_price.setText("");
        tf_date_sale.setText("");
        tf_total.setText("");
    }

    private void table_update() {
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_tienda.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[] {
                    fila.get("id"),
                    fila.get("name"),
                    fila.get("quantities_sold"),
                    fila.get("unit_price"),
                    fila.get("date_sale"),
                    fila.get("total"),
            });
        }
    }
    
    private void read(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read
        // TODO add your handling code here:
        List<Map<String, Object>> datos = bd.leer(configuration, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_tienda.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[] {
                    fila.get("id"),
                    fila.get("name"),
                    fila.get("quantities_sold"),
                    fila.get("unit_price"),
                    fila.get("date_sale"),
                    fila.get("total"),
            });
        }
    }//GEN-LAST:event_read

    private void create(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create
        // TODO add your handling code here:
        int id = Integer.parseInt(tf_id.getText());
        Map datos = new HashMap();
        datos.put(campos[0], tf_name.getText());
        datos.put(campos[1], tf_quantities_sold.getText());
        datos.put(campos[2], tf_unit_price.getText());
        datos.put(campos[3], tf_date_sale.getText());
        datos.put(campos[4], tf_total.getText());
        
        bd.actualizar(id, datos, configuration, tabla);
        
        clean();
        table_update();
    }//GEN-LAST:event_create

    private void tf_date_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_date_saleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_date_saleActionPerformed

    private void tf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_totalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_read;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_id;
    private javax.swing.JLabel lab_tittle;
    private javax.swing.JLabel lb_date_sale;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_quantities_sold;
    private javax.swing.JLabel lb_sale_price;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTable tbl_tienda;
    private javax.swing.JTextField tf_date_sale;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_quantities_sold;
    private javax.swing.JTextField tf_total;
    private javax.swing.JTextField tf_unit_price;
    // End of variables declaration//GEN-END:variables

    String [] configuration = {"localhost", "root", "adminadmin", "portfolio"};
    String tabla = "sales";
    String [] campos = {"name", "quantities_sold", "unit_price", "date_sale", "total"};
    MySQLGenerico bd = new MySQLGenerico();
}
